import { PermissionKey } from "@prisma/client";
import { requirePermission } from "@/lib/permissions";
import { db } from "@/lib/db";
import { createUserAction, updateUserAction, adminResetPasswordAction, deleteUserAction } from "@/app/actions";
export const dynamic="force-dynamic";
const roles=["OWNER","ADMIN","MANAGER","STAFF","PRODUCTION","ACCOUNTING","VIEWER"];
export default async function UsersPage(){
 const actor=await requirePermission(PermissionKey.USERS_MANAGE);
 const users=await db.user.findMany({orderBy:[{role:"asc"},{name:"asc"}]});
 return <><div className="top"><div><h1>Users & Roles</h1><p className="muted">Create staff profiles, assign access, reset passwords, and disable accounts.</p></div></div>
 <section className="card section"><h2>Add user</h2><form action={createUserAction} className="formGrid">
 <input name="name" placeholder="Full name" required/><input name="email" type="email" placeholder="Email" required/><input name="jobTitle" placeholder="Job title"/><input name="phone" placeholder="Phone"/>
 <select name="role" defaultValue="STAFF">{roles.filter(r=>actor.role==="OWNER"||r!=="OWNER").map(r=><option key={r}>{r}</option>)}</select>{actor.role==="OWNER"?<><select name="customerAccessMode" defaultValue="ASSIGNED"><option value="ASSIGNED">Own assigned customers only</option><option value="ALL">All customer information</option></select><select name="featureAccessMode" defaultValue="ASSIGNED"><option value="ASSIGNED">Assigned feature categories only</option><option value="ALL">All TITAN features</option></select></>:<><input type="hidden" name="customerAccessMode" value="ASSIGNED"/><input type="hidden" name="featureAccessMode" value="ASSIGNED"/></>}<input name="password" type="password" placeholder="Temporary password (8+ characters)" minLength={8} required/><button>Create user</button></form></section>
 <section className="section"><h2>Accounts</h2><div className="stack">{users.map(u=><div className="card" key={u.id}><form action={updateUserAction} className="formGrid"><input type="hidden" name="id" value={u.id}/><input name="name" defaultValue={u.name}/><input name="email" type="email" defaultValue={u.email}/><input name="jobTitle" defaultValue={u.jobTitle||""} placeholder="Job title"/><input name="phone" defaultValue={u.phone||""} placeholder="Phone"/>{u.role==="OWNER"&&actor.role!=="OWNER"?<><input type="hidden" name="role" value="OWNER"/><input value="OWNER" disabled/></>:<select name="role" defaultValue={u.role}>{roles.filter(r=>actor.role==="OWNER"||r!=="OWNER").map(r=><option key={r}>{r}</option>)}</select>}{actor.role==="OWNER"?<><select name="customerAccessMode" defaultValue={u.role==="OWNER"?"ALL":u.customerAccessMode} disabled={u.role==="OWNER"}><option value="ASSIGNED">Own assigned customers only</option><option value="ALL">All customer information</option></select>{u.role==="OWNER"&&<input type="hidden" name="customerAccessMode" value="ALL"/>}<select name="featureAccessMode" defaultValue={u.role==="OWNER"?"ALL":u.featureAccessMode} disabled={u.role==="OWNER"}><option value="ASSIGNED">Assigned feature categories only</option><option value="ALL">All TITAN features</option></select>{u.role==="OWNER"&&<input type="hidden" name="featureAccessMode" value="ALL"/>}</>:<><input value={u.customerAccessMode==="ALL"?"All customer information":"Own assigned customers only"} disabled/><input value={u.featureAccessMode==="ALL"?"All TITAN features":"Assigned feature categories only"} disabled/></>}<label><input type="checkbox" name="active" defaultChecked={u.active}/> Active</label><button>Save profile</button></form>
 <div className="muted">Last login: {u.lastLoginAt?u.lastLoginAt.toLocaleString("en-CA"):"Never"} · {u.mustChangePassword?"Password change required":"Password current"}</div>
 <form action={adminResetPasswordAction} className="inlineForm"><input type="hidden" name="id" value={u.id}/><input name="password" type="password" minLength={8} placeholder="New temporary password" required/><button>Reset password</button></form>
 {actor.role==="OWNER"&&u.role!=="OWNER"&&u.id!==actor.id?<form action={deleteUserAction}><input type="hidden" name="id" value={u.id}/><button className="danger">Delete user</button></form>:null}</div>)}</div></section></>;
}
